name: Chainguard Registry Example

on:
  push:
    branches: ['main']

permissions:
  contents: read
  id-token: write  # This is needed for OIDC federation.

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chainguard-dev/actions/setup-chainctl@main
        with:
          identity: c854956e2b18fd58d82a4167fac4cf48dbf452a6/10de749e50d7053c
      - run: docker pull cgr.dev/chainguard/node
